filter:
    excluded_paths:
        - tests/*
build:
    environment:
        php: 7.0
    cache:
        disabled:             false
        directories:
            - ~/.composer/cache
            - tmp/
            - vendor/
    dependencies:
        override:
            - composer self-update
            - composer update --with-dependencies -v -o
    tests:
        override:
            - jshint-run $(ls public_html/js/*.js)
            - shellcheck-run -s bash $(ls scripts/*/*.sh)
            - csslint-run --exclude-list=public_html/css/domains.css,public_html/css/minified,public_html/css/reset.css,public_html/css/price_win.css public_html/css
            -
                command: 'vendor/bin/phpunit --bootstrap tests/bootstrap.php tests/ -v --coverage-clover coverage.xml --whitelist src/'
                #command: 'phpdbg -qrr vendor/bin/phpunit --bootstrap tests/bootstrap.php tests/ -v --coverage-clover coverage.xml --whitelist src/'
                coverage:
                    file: 'coverage.xml'
                    format: 'clover'
checks:
    php:
        uppercase_constants: true
        return_doc_comment_if_not_inferrable: true
        return_doc_comments: true
        remove_extra_empty_lines: true
        phpunit_assertions: true
        avoid_fixme_comments: true
        param_doc_comment_if_not_inferrable: true
        parameter_doc_comments: true
        simplify_boolean_return: true
        remove_extra_empty_lines: true
        property_assignments: true
        properties_in_camelcaps: true
        precedence_mistakes: true
        precedence_in_conditions: true
        phpunit_assertions: true
        php5_style_constructor: true
        parse_doc_comments: true
        parameters_in_camelcaps: true
        parameter_doc_comments: true
        param_doc_comment_if_not_inferrable: true
        one_class_per_file: true
        non_commented_empty_catch_block: true
        no_unnecessary_if: true
        no_trailing_whitespace: true
        no_short_open_tag: true
        no_non_implemented_abstract_methods: true
        no_goto: true
        no_long_variable_names:
            maximum: '25'
        more_specific_types_in_doc_comments: true
        missing_arguments: true
        instanceof_class_exists: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: true
        fix_doc_comments: true
        encourage_shallow_comparison: true
        deprecated_code_usage: true
        deadlock_detection_in_loops: true
        comparison_always_same_result: true
        code_rating: true
        blank_line_after_namespace_declaration: true
        avoid_usage_of_logical_operators: true
        avoid_perl_style_comments: true
        avoid_fixme_comments: true
        avoid_duplicate_types: true
        avoid_corrupting_byteorder_marks: true
        avoid_closing_tag: true
        argument_type_checks: true
coding_style:
    php:
        indentation:
            general:
                use_tabs: true
                size: 4
            switch:
                indent_case: true
        spaces:
            general:
                linefeed_character: newline
            before_parentheses:
                function_declaration: false
                closure_definition: false
                function_call: false
                if: true
                for: true
                while: true
                switch: true
                catch: true
                array_initializer: false
            around_operators:
                assignment: true
                logical: true
                equality: true
                relational: true
                bitwise: true
                additive: true
                multiplicative: true
                shift: true
                unary_additive: false
                concatenation: false
                negation: false
            before_left_brace:
                class: true
                function: true
                if: true
                else: true
                for: true
                while: true
                do: true
                switch: true
                try: true
                catch: true
                finally: true
            before_keywords:
                else: true
                while: true
                catch: true
                finally: true
            within:
                brackets: false
                array_initializer: false
                grouping: false
                function_call: false
                function_declaration: false
                if: false
                for: false
                while: false
                switch: false
                catch: false
                type_cast: false
            ternary_operator:
                before_condition: true
                after_condition: true
                before_alternative: true
                after_alternative: true
                in_short_version: false
            other:
                before_comma: false
                after_comma: true
                before_semicolon: false
                after_semicolon: true
                after_type_cast: true
        braces:
            classes_functions:
                class: end-of-line
                function: end-of-line
                closure: end-of-line
            if:
                opening: end-of-line
                always: false
                else_on_new_line: false
            for:
                opening: end-of-line
                always: false
            while:
                opening: end-of-line
                always: false
            do_while:
                opening: end-of-line
                always: false
                while_on_new_line: false
            switch:
                opening: end-of-line
            try:
                opening: end-of-line
                catch_on_new_line: false
                finally_on_new_line: false
        upper_lower_casing:
            keywords:
                general: lower
            constants:
                true_false_null: upper
