env:
  global:
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)
language: php
os: linux
dist: trusty
sudo: false
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
cache:
  directories:
    - $HOME/.composer/cache/files
    - tmp/pear/download/
    - vendor/
addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN
before_script:
  - mkdir -p build/logs
  - phpenv config-rm xdebug.ini
  - pear install pear/XML_RPC2
  - phpenv rehash
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --dev --prefer-source
script: 
  - if [ "$TRAVIS_PHP_VERSION" = "7.0" ]; then phpdbg -qrr vendor/bin/phpunit --bootstrap tests/bootstrap.php tests/ -v --coverage-clover coverage.xml --whitelist src/; fi;
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ]; then vendor/bin/phpunit --bootstrap tests/bootstrap.php tests/ -v; fi
after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then travis_retry vendor/bin/test-reporter --coverage-report=coverage.xml; fi
  - if [ "$TRAVIS_PHP_VERSION" = "7.0" ]; then travis_retry bash <(curl -s https://codecov.io/bash); fi;
  - if [ "$TRAVIS_PHP_VERSION" = "7.0" ]; then travis_retry php vendor/bin/coveralls -v --coverage_clover=coverage.xml; fi;
  - if [ "$TRAVIS_PHP_VERSION" = "7.0" ]; then travis_retry php vendor/bin/codacycoverage clover coverage.xml; fi;
