language: php
os: linux
dist: trusty
sudo: false
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

install: composer update --dev -o
script: vendor/phpunit/phpunit/phpunit -c phpunit.xml.dist

